stack_name: git_sample
version: '2'
services:
  test1:
    build: .
    command: ./nothing.sh
    scaling:
      min: 1
      max: 12
      on_alert:
        alert5: "+2"
        alert6: "/2"
  inserter:
    build: .
    command: ./writer.sh
    networks:
      - default
      - fodocker
metrics:
  - metric2
alerts:
  alert5:
    metric2: ">=70"
  alert6:
    metric2: "<=30"
networks:
  fodocker:
    external:
      name: test_default
